CREATE DATABASE `cracktool` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;

USE `cracktool`;

CREATE TABLE `cracktool` (
`string` VARCHAR(64) BINARY NOT NULL DEFAULT '',
`nb_char` SMALLINT(255) UNSIGNED NOT NULL DEFAULT '0',
`create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
`md2` VARCHAR(32) NOT NULL DEFAULT '',
`md4` VARCHAR(32) NOT NULL DEFAULT '',
`md5` VARCHAR(32) NOT NULL DEFAULT '',
`sha1` VARCHAR(40) NOT NULL DEFAULT '',
`sha256` VARCHAR(64) NOT NULL DEFAULT '',
`sha384` VARCHAR(96) NOT NULL DEFAULT '',
`sha512` VARCHAR(128) NOT NULL DEFAULT '',
`ripemd128` VARCHAR(32) NOT NULL DEFAULT '',
`ripemd160` VARCHAR(40) NOT NULL DEFAULT '',
`ripemd256` VARCHAR(64) NOT NULL DEFAULT '',
`ripemd320` VARCHAR(80) NOT NULL DEFAULT '',
`whirlpool` VARCHAR(128) NOT NULL DEFAULT '',
`tiger128,3` VARCHAR(32) NOT NULL DEFAULT '',
`tiger160,3` VARCHAR(40) NOT NULL DEFAULT '',
`tiger192,3` VARCHAR(48) NOT NULL DEFAULT '',
`tiger128,4` VARCHAR(32) NOT NULL DEFAULT '',
`tiger160,4` VARCHAR(40) NOT NULL DEFAULT '',
`tiger192,4` VARCHAR(48) NOT NULL DEFAULT '',
`snefru` VARCHAR(64) NOT NULL DEFAULT '',
`gost` VARCHAR(64) NOT NULL DEFAULT '',
`adler32` VARCHAR(8) NOT NULL DEFAULT '',
`crc32` VARCHAR(8) NOT NULL DEFAULT '',
`crc32b` VARCHAR(8) NOT NULL DEFAULT '',
`haval128,3` VARCHAR(32) NOT NULL DEFAULT '',
`haval160,3` VARCHAR(40) NOT NULL DEFAULT '',
`haval192,3` VARCHAR(48) NOT NULL DEFAULT '',
`haval224,3` VARCHAR(56) NOT NULL DEFAULT '',
`haval256,3` VARCHAR(64) NOT NULL DEFAULT '',
`haval128,4` VARCHAR(32) NOT NULL DEFAULT '',
`haval160,4` VARCHAR(40) NOT NULL DEFAULT '',
`haval192,4` VARCHAR(48) NOT NULL DEFAULT '',
`haval224,4` VARCHAR(56) NOT NULL DEFAULT '',
`haval256,4` VARCHAR(64) NOT NULL DEFAULT '',
`haval128,5` VARCHAR(32) NOT NULL DEFAULT '',
`haval160,5` VARCHAR(40) NOT NULL DEFAULT '',
`haval192,5` VARCHAR(48) NOT NULL DEFAULT '',
`haval224,5` VARCHAR(56) NOT NULL DEFAULT '',
`haval256,5` VARCHAR(64) NOT NULL DEFAULT '',
PRIMARY KEY (`string`(64)),
INDEX (`nb_char`),
INDEX (`md4`),
INDEX (`md5`),
INDEX (`sha1`),
INDEX (`sha256`),
INDEX (`sha384`),
INDEX (`sha512`),
INDEX (`ripemd128`),
INDEX (`ripemd160`),
INDEX (`ripemd256`),
INDEX (`ripemd320`),
INDEX (`whirlpool`),
INDEX (`tiger128,3`),
INDEX (`tiger160,3`),
INDEX (`tiger192,3`),
INDEX (`tiger128,4`),
INDEX (`tiger160,4`),
INDEX (`tiger192,4`),
INDEX (`snefru`),
INDEX (`gost`),
INDEX (`adler32`),
INDEX (`crc32`),
INDEX (`crc32b`),
INDEX (`haval128,3`),
INDEX (`haval160,3`),
INDEX (`haval192,3`),
INDEX (`haval224,3`),
INDEX (`haval256,3`),
INDEX (`haval128,4`),
INDEX (`haval160,4`),
INDEX (`haval192,4`),
INDEX (`haval224,4`),
INDEX (`haval256,4`),
INDEX (`haval128,5`),
INDEX (`haval160,5`),
INDEX (`haval192,5`),
INDEX (`haval224,5`),
INDEX (`haval256,5`)
) ENGINE = MyISAM CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT='cracktool';


CREATE TABLE `history` (
`string` VARCHAR(128) NOT NULL DEFAULT '',
`action` ENUM('add_string','crack_succeed','crack_failed') NOT NULL DEFAULT 'add_string',
`create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
INDEX (`string`(128)),
INDEX (`action`),
INDEX (`create_datetime`)
) ENGINE = MyISAM CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT='history';

CREATE TABLE `to_crack` (
`hash` VARCHAR(128) BINARY NOT NULL DEFAULT '',
`email` VARCHAR(255) NOT NULL DEFAULT '',
`language` ENUM('en','fr','de','es','it','pt') NOT NULL DEFAULT 'en',
`create_datetime` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
INDEX (`hash`),
INDEX (`email`),
INDEX (`create_datetime`)
) ENGINE = MyISAM CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT='hash à cracker';

CREATE TABLE `text` (
`id_text` VARCHAR(255) NOT NULL DEFAULT '',
`file` VARCHAR(255) NOT NULL DEFAULT '',
`en` VARCHAR(255) NOT NULL DEFAULT '',
`fr` VARCHAR(255) NOT NULL DEFAULT '',
`de` VARCHAR(255) NOT NULL DEFAULT '',
`es` VARCHAR(255) NOT NULL DEFAULT '',
`it` VARCHAR(255) NOT NULL DEFAULT '',
`pt` VARCHAR(255) NOT NULL DEFAULT '',
INDEX (`id_text`(255)),
INDEX (`file`)
) ENGINE = MyISAM CHARACTER SET utf8 COLLATE utf8_general_ci COMMENT='text';

INSERT INTO `text` (`id_text`,`file`,`en`,`fr`)
VALUES ('title','index.php','HashTool hash and crack md2, md4, md5, sha1, sha256, ripmd128, whirlpool, snefru, gost, adler32, crc32, haval...','HashTool Hasher et cracker en md2, md4, md5, sha1, sha256, ripmd128, whirlpool, snefru, gost, adler32, crc32, haval...'),
('description','index.php','HashTool hash and crack md2, md4, md5, sha1, sha256, sha384, sha512, ripmd128, ripmd160, ripmd256, ripmd320, whirlpool, tiger128,3, tiger160,3, tiger192,3, tiger128,4, tiger160,4, tiger192,4, snefru, gost, adler32, crc32, crc32b, haval128,3, haval160,3, haval192,3, haval224,3, haval256,3, haval128,4, haval160,4, haval192,4, haval224,4, haval256,4, haval128,5, haval160,5, haval192,5, haval224,5, haval256,5.','HashTool hasher et cracker en md2, md4, md5, sha1, sha256, sha384, sha512, ripmd128, ripmd160, ripmd256, ripmd320, whirlpool, tiger128,3, tiger160,3, tiger192,3, tiger128,4, tiger160,4, tiger192,4, snefru, gost, adler32, crc32, crc32b, haval128,3, haval160,3, haval192,3, haval224,3, haval256,3, haval128,4, haval160,4, haval192,4, haval224,4, haval256,4, haval128,5, haval160,5, haval192,5, haval224,5, haval256,5.'),
('hash string','index.php','Hash a string:','Hasher une chaine de caractère:'),
('crack hash','index.php','Crack a hash:','Cracker un hash:'),
('all','index.php','All','Tout'),
('nothing','index.php','Nothing','Rien'),
('to hash','index.php','To hash','Hasher'),
('to crack','index.php','To crack','Cracker'),
('history','index.php','History','Historique'),
('hash type','hash.php','Hash type','Type de hash'),
('hash','hash.php','Hash','Hash'),
('string','crack.php','String','Chaîne de caractère'),
('hash type','crack.php','Hash type','Type de hash'),
('hash','crack.php','Hash','Hash'),
('crack of','crack.php','Crack of','Crackage de'),
('no solution','crack.php','None solution find.','Aucune solution trouvé.'),
('msg email','crack.php','You can put your email in order to contact you when the hash will be cracked.','Vous pouvez nous laisser votre email pour vous contacter lorsque le hash sera cracké.'),
('msg history','history.php','History of actions','Historique des actions'),
('value','history.php','Value','Valeur'),
('action','history.php','Action','Action'),
('date','history.php','Date','Date'),
('add_string','history.php','String added','Chaîne de caractère ajoutée'),
('crack_succeed','history.php','Crack succeed','Crackage réussi'),
('crack_failed','history.php','Crack failed','Crackage échoué')